/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../../../..";

export interface SearchDealsResponse {
    status: Vellum.common.ResponseStatus;
    results: Vellum.common.Deal[];
}
