/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RevertRevertApi from "../../../../../..";

export interface UpdateAccountCredentialsRequest {
    xRevertApiToken: string;
    clientId?: string;
    clientSecret?: string;
    scopes?: string[];
    tpId: RevertRevertApi.common.Tpid;
    isRevertApp: boolean;
    appId: string;
    botToken?: string;
}
