/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../..";
import * as Revert from "../../../../../../../../api";
import * as core from "../../../../../../../../core";

export const CreateFieldMappingResponse: core.serialization.ObjectSchema<
    serializers.crm.fieldMapping.CreateFieldMappingResponse.Raw,
    Revert.crm.fieldMapping.CreateFieldMappingResponse
> = core.serialization.object({
    status: core.serialization.lazy(async () => (await import("../../../../../../..")).common.ResponseStatus),
});

export declare namespace CreateFieldMappingResponse {
    interface Raw {
        status: serializers.common.ResponseStatus.Raw;
    }
}
