/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../..";
import * as RevertRevertApi from "../../../../../../../../api";
import * as core from "../../../../../../../../core";

export const GetFieldMappingResponse: core.serialization.ObjectSchema<
    serializers.crm.fieldMapping.GetFieldMappingResponse.Raw,
    RevertRevertApi.crm.fieldMapping.GetFieldMappingResponse
> = core.serialization.object({
    canAddCustomMapping: core.serialization.boolean(),
    mappableFields: core.serialization.list(
        core.serialization.lazyObject(
            async () => (await import("../../../../../../..")).crm.fieldMapping.MappableFieldType
        )
    ),
    fieldList: core.serialization.unknown(),
});

export declare namespace GetFieldMappingResponse {
    interface Raw {
        canAddCustomMapping: boolean;
        mappableFields: serializers.crm.fieldMapping.MappableFieldType.Raw[];
        fieldList?: unknown;
    }
}
