/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ConnectionStatus = "SUCCESS" | "FAILED";

export const ConnectionStatus = {
    Success: "SUCCESS",
    Failed: "FAILED",
} as const;
