/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../..";

export interface CreateConnectionWebhookResponse {
    status: Vellum.common.ResponseStatus;
    webhookUrl: string;
    createdAt: string;
    secret: string;
    error?: string;
    errorMessage?: unknown;
}
