/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../..";

export interface DeleteConnectionWebhookResponse {
    status: Vellum.common.ResponseStatus;
    error?: string;
    errorMessage?: unknown;
}
