/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../..";

export interface DeleteConnectionResponse {
    status: Revert.common.ResponseStatus;
    deleted: Revert.common.Connection;
}
