/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../..";

export interface GetConnectionResponse extends Revert.common.Connection {
    error?: string;
}
