/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../..";

export interface GetConnectionWebhookResponse {
    status: Revert.common.ResponseStatus;
    webhook?: unknown;
    error?: string;
    errorMessage?: unknown;
}
