/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const ResponseStatus: core.serialization.Schema<
    serializers.common.ResponseStatus.Raw,
    Revert.common.ResponseStatus
> = core.serialization.enum_(["ok", "error"]);

export declare namespace ResponseStatus {
    type Raw = "ok" | "error";
}
