/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const TicketStatus: core.serialization.Schema<serializers.common.TicketStatus.Raw, Revert.common.TicketStatus> =
    core.serialization.enum_(["open", "close", "in_progress"]);

export declare namespace TicketStatus {
    type Raw = "open" | "close" | "in_progress";
}
