/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../../../..";

export interface App {
    id: string;
    tpId: Vellum.common.Tpid;
    scope?: string[];
    appClientId?: string;
    appClientSecret?: string;
    ownerAccountPublicToken: string;
    account?: Vellum.common.Account;
    connections?: Vellum.common.Connection[];
    isRevertApp: boolean;
}
