/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../../../..";

export interface Connection {
    tpId: Vellum.common.Tpid;
    tpAccessToken: string;
    tpRefreshToken?: string;
    tpCustomerId: string;
    tId: string;
    tpAccountUrl?: string;
    ownerAccountPublicToken: string;
    appClientId?: string;
    appClientSecret?: string;
    app?: Vellum.common.App;
}
