/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RevertRevertApi from "../../../../..";

export interface RevertUser {
    id: string;
    domain: string;
    email: string;
    accountId: string;
    account?: RevertRevertApi.common.Account;
}
