/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TicketStatus = "open" | "close" | "in_progress";

export const TicketStatus = {
    Open: "open",
    Close: "close",
    InProgress: "in_progress",
} as const;
