/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TicketPriority = "urgent" | "high" | "medium" | "low" | "lowest";

export const TicketPriority = {
    Urgent: "urgent",
    High: "high",
    Medium: "medium",
    Low: "low",
    Lowest: "lowest",
} as const;
