/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Tpid = "hubspot" | "zohocrm" | "sfdc" | "pipedrive" | "slack" | "closecrm" | "ms_dynamics_365_sales";

export const Tpid = {
    Hubspot: "hubspot",
    Zohocrm: "zohocrm",
    Sfdc: "sfdc",
    Pipedrive: "pipedrive",
    Slack: "slack",
    Closecrm: "closecrm",
    MsDynamics365Sales: "ms_dynamics_365_sales",
} as const;
