/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../../..";

export interface CreateFieldMappingRequest {
    /**
     * Your public key, to be used on the frontend usually.
     */
    xRevertPublicToken: string;
    /**
     * The unique customer id used when the customer linked their account.
     */
    xRevertTId: string;
    /**
     * The temp used to identify tenant.
     */
    xRevertTToken: string;
    body: Revert.CreateFieldMappingRequestBody;
}
