/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetFieldMappingsRequest {
    /**
     * Your official API key for accessing revert apis.
     */
    xRevertApiToken: string;
    /**
     * The unique customer id used when the customer linked their account.
     */
    xRevertTId: string;
}
