/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../..";

export interface DeleteAccountFieldMappingConfigResponse {
    status: Revert.common.ResponseStatus;
}
