/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RevertRevertApi from "../../../../..";

export interface GetNoteResponse {
    status: RevertRevertApi.common.ResponseStatus;
    result: RevertRevertApi.common.Note;
}
