/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../../../..";

export interface GetUserResponse {
    status: Vellum.common.ResponseStatus;
    result: Vellum.common.User;
}
