/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../..";
import * as Revert from "../../../../../../../api";
import * as core from "../../../../../../../core";

export const SearchTasksRequest: core.serialization.Schema<
    serializers.crm.SearchTasksRequest.Raw,
    Omit<
        Revert.crm.SearchTasksRequest,
        "fields" | "pageSize" | "cursor" | "xRevertApiToken" | "xRevertTId" | "xApiVersion"
    >
> = core.serialization.object({
    searchCriteria: core.serialization.unknown(),
});

export declare namespace SearchTasksRequest {
    interface Raw {
        searchCriteria?: unknown;
    }
}
