/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const GetDepartmentResponse: core.serialization.ObjectSchema<
    serializers.ats.GetDepartmentResponse.Raw,
    Revert.ats.GetDepartmentResponse
> = core.serialization.object({
    status: core.serialization.lazy(async () => (await import("../../../../..")).common.ResponseStatus),
    result: core.serialization.unknown(),
});

export declare namespace GetDepartmentResponse {
    interface Raw {
        status: serializers.common.ResponseStatus.Raw;
        result?: unknown;
    }
}
