/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const CreateOrUpdateDealRequest: core.serialization.ObjectSchema<
    serializers.crm.CreateOrUpdateDealRequest.Raw,
    Revert.crm.CreateOrUpdateDealRequest
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).common.DealWrite));

export declare namespace CreateOrUpdateDealRequest {
    interface Raw extends serializers.common.DealWrite.Raw {}
}
