/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as RevertRevertApi from "../../../../api";
import * as core from "../../../../core";

export const CreateConnectionWebhookRequest: core.serialization.ObjectSchema<
    serializers.CreateConnectionWebhookRequest.Raw,
    RevertRevertApi.CreateConnectionWebhookRequest
> = core.serialization.object({
    webhookUrl: core.serialization.string(),
});

export declare namespace CreateConnectionWebhookRequest {
    interface Raw {
        webhookUrl: string;
    }
}
