/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as RevertRevertApi from "../../../../api";
import * as core from "../../../../core";

export const DeleteConnectionResponse: core.serialization.ObjectSchema<
    serializers.DeleteConnectionResponse.Raw,
    RevertRevertApi.DeleteConnectionResponse
> = core.serialization.object({
    status: core.serialization.lazy(async () => (await import("../../..")).common.ResponseStatus),
    deleted: core.serialization.lazyObject(async () => (await import("../../..")).common.Connection),
});

export declare namespace DeleteConnectionResponse {
    interface Raw {
        status: serializers.common.ResponseStatus.Raw;
        deleted: serializers.common.Connection.Raw;
    }
}
