/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Vellum from "../../../../api";
import * as core from "../../../../core";

export const GetConnectionResponse: core.serialization.ObjectSchema<
    serializers.GetConnectionResponse.Raw,
    Vellum.GetConnectionResponse
> = core.serialization
    .object({
        error: core.serialization.string().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).common.Connection));

export declare namespace GetConnectionResponse {
    interface Raw extends serializers.common.Connection.Raw {
        error?: string | null;
    }
}
