/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Revert from "../../../../api";
import * as core from "../../../../core";

export const GetConnectStatusResponse: core.serialization.ObjectSchema<
    serializers.GetConnectStatusResponse.Raw,
    Revert.GetConnectStatusResponse
> = core.serialization.object({
    publicToken: core.serialization.string(),
    status: core.serialization.lazy(async () => (await import("../../..")).ConnectionStatus),
    integrationName: core.serialization.string(),
    tenantId: core.serialization.string(),
    tenantSecretToken: core.serialization.string().optional(),
});

export declare namespace GetConnectStatusResponse {
    interface Raw {
        publicToken: string;
        status: serializers.ConnectionStatus.Raw;
        integrationName: string;
        tenantId: string;
        tenantSecretToken?: string | null;
    }
}
