/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Revert from "../../../../api";
import * as core from "../../../../core";

export const ImportConnectionsResponse: core.serialization.ObjectSchema<
    serializers.ImportConnectionsResponse.Raw,
    Revert.ImportConnectionsResponse
> = core.serialization.object({
    status: core.serialization.lazy(async () => (await import("../../..")).common.ResponseStatus),
});

export declare namespace ImportConnectionsResponse {
    interface Raw {
        status: serializers.common.ResponseStatus.Raw;
    }
}
