/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../..";
import * as RevertRevertApi from "../../../../../../../api";
import * as core from "../../../../../../../core";

export const CreateTelemetryEntryRequest: core.serialization.Schema<
    serializers.internal.CreateTelemetryEntryRequest.Raw,
    Omit<RevertRevertApi.internal.CreateTelemetryEntryRequest, "xRevertApiToken">
> = core.serialization.object({
    numberOfUsers: core.serialization.number(),
    numberOfAccounts: core.serialization.number(),
    numberOfConnections: core.serialization.number(),
    numberOfApiCalls: core.serialization.number(),
});

export declare namespace CreateTelemetryEntryRequest {
    interface Raw {
        numberOfUsers: number;
        numberOfAccounts: number;
        numberOfConnections: number;
        numberOfApiCalls: number;
    }
}
