/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../../../errors";
import * as RevertRevertApi from "../../../../..";

export class UnAuthorizedError extends errors.RevertRevertApiError {
    constructor(body: RevertRevertApi.common.BaseError) {
        super({
            message: "UnAuthorizedError",
            statusCode: 401,
            body: body,
        });
        Object.setPrototypeOf(this, UnAuthorizedError.prototype);
    }
}
