/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import { FieldMapping as FieldMapping_ } from "../resources/fieldMapping/client/Client";

export declare namespace FieldMapping {
    interface Options {
        environment?: core.Supplier<environments.VellumEnvironment | string>;
    }

    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}

export class FieldMapping {
    constructor(protected readonly _options: FieldMapping.Options = {}) {}

    protected _fieldMapping: FieldMapping_ | undefined;

    public get fieldMapping(): FieldMapping_ {
        return (this._fieldMapping ??= new FieldMapping_(this._options));
    }
}
