/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const CreateOrUpdateContactRequest: core.serialization.ObjectSchema<
    serializers.crm.CreateOrUpdateContactRequest.Raw,
    Revert.crm.CreateOrUpdateContactRequest
> = core.serialization.lazyObject(async () => (await import("../../../../..")).common.ContactWrite);

export declare namespace CreateOrUpdateContactRequest {
    type Raw = serializers.common.ContactWrite.Raw;
}
