/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as RevertRevertApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const GetContactResponse: core.serialization.ObjectSchema<
    serializers.crm.GetContactResponse.Raw,
    RevertRevertApi.crm.GetContactResponse
> = core.serialization.object({
    status: core.serialization.lazy(async () => (await import("../../../../..")).common.ResponseStatus),
    result: core.serialization.lazyObject(async () => (await import("../../../../..")).common.Contact),
});

export declare namespace GetContactResponse {
    interface Raw {
        status: serializers.common.ResponseStatus.Raw;
        result: serializers.common.Contact.Raw;
    }
}
