/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         dealId: "14189075991"
 *     }
 */
export interface CompanyAssociation {
    /** The id of the deal to associate with company */
    dealId?: string;
}
