/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         dealId: "14189075991"
 *     }
 */
export interface ContactAssociation {
    /** The id of the deal to associate with contact */
    dealId?: string;
    /** The id of lead to associate with contact for close crm */
    leadId?: string;
}
