/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         dealId: "14189075991",
 *         companyId: "15661756020"
 *     }
 */
export interface LeadAssociation {
    /** The id of the contact to associate with lead */
    contactId?: string;
    /** The id of the company to associate with lead */
    companyId?: string;
    /** The id of the deal to associate with lead */
    dealId?: string;
}
