/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         dealId: "535586000000287437"
 *     }
 */
export interface TaskAssociation {
    /** The id of the deal to associate with task */
    dealId?: string;
}
