/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RevertRevertApi from "../../../../..";

export interface GetAnalyticsResponse {
    status: RevertRevertApi.common.ResponseStatus;
    result: RevertRevertApi.common.Analytics;
}
