/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RevertRevertApi from "../../../../..";

export interface GetCommentsResponse {
    status: RevertRevertApi.common.ResponseStatus;
    next?: string;
    previous?: string;
    results?: unknown;
}
