/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../../../..";

export interface GetCommentResponse {
    status: Vellum.common.ResponseStatus;
    result?: unknown;
}
