/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Vellum from "../../../../../../api";
import * as core from "../../../../../../core";

export const GetCommentResponse: core.serialization.ObjectSchema<
    serializers.ticket.GetCommentResponse.Raw,
    Vellum.ticket.GetCommentResponse
> = core.serialization.object({
    status: core.serialization.lazy(async () => (await import("../../../../..")).common.ResponseStatus),
    result: core.serialization.unknown(),
});

export declare namespace GetCommentResponse {
    interface Raw {
        status: serializers.common.ResponseStatus.Raw;
        result?: unknown;
    }
}
