/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../../../..";

export interface SearchContactsResponse {
    status: Vellum.common.ResponseStatus;
    results: Vellum.common.Contact[];
}
