/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RevertRevertApi from "../../../../..";

export interface SearchContactsResponse {
    status: RevertRevertApi.common.ResponseStatus;
    results: RevertRevertApi.common.Contact[];
}
