/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../../../..";

export interface GetFieldMappingConfigResponse {
    canAddCustomMapping: boolean;
    mappableFields: Revert.crm.MappableFieldType[];
    fieldList?: unknown;
}
