/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../../../..";

export interface CreateOrUpdateTaskResponse {
    status: Vellum.common.ResponseStatus;
    message: string;
    result?: unknown;
}
