/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../../../..";

export interface CreateOrUpdateTaskRequest extends Revert.common.TaskWrite {
    /** Any fields that are not unified yet/non-unifiable come inside this `json` object. */
    additional?: unknown;
}
