/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RevertRevertApi from "../../../../..";

export interface CreateOrUpdateTaskResponse {
    status: RevertRevertApi.common.ResponseStatus;
    message: string;
    result?: unknown;
}
