/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../../../..";

export interface GetTaskResponse {
    status: Revert.common.ResponseStatus;
    result: Revert.common.Task;
}
