/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const CreateOrUpdateTaskRequest: core.serialization.ObjectSchema<
    serializers.crm.CreateOrUpdateTaskRequest.Raw,
    Revert.crm.CreateOrUpdateTaskRequest
> = core.serialization
    .object({
        additional: core.serialization.unknown(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).common.TaskWrite));

export declare namespace CreateOrUpdateTaskRequest {
    interface Raw extends serializers.common.TaskWrite.Raw {
        additional?: unknown;
    }
}
