/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Vellum from "../../../../../../api";
import * as core from "../../../../../../core";

export const CreateOrUpdateUserRequest: core.serialization.ObjectSchema<
    serializers.crm.CreateOrUpdateUserRequest.Raw,
    Vellum.crm.CreateOrUpdateUserRequest
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).common.UserWrite));

export declare namespace CreateOrUpdateUserRequest {
    interface Raw extends serializers.common.UserWrite.Raw {}
}
