/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as RevertRevertApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const GetAccountDetailsResponse: core.serialization.ObjectSchema<
    serializers.internal.GetAccountDetailsResponse.Raw,
    RevertRevertApi.internal.GetAccountDetailsResponse
> = core.serialization.object({
    account: core.serialization.lazyObject(async () => (await import("../../../../..")).common.Account),
});

export declare namespace GetAccountDetailsResponse {
    interface Raw {
        account: serializers.common.Account.Raw;
    }
}
