/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RevertRevertApi from "../../../../..";

export interface CreateOrUpdateCompanyRequest extends RevertRevertApi.common.Company {
    associations?: RevertRevertApi.common.CompanyAssociation;
}
