/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../../../..";

export interface SearchCompaniesResponse {
    status: Revert.common.ResponseStatus;
    results: Revert.common.Company[];
}
