/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const DeleteJobResponse: core.serialization.ObjectSchema<
    serializers.ats.DeleteJobResponse.Raw,
    Revert.ats.DeleteJobResponse
> = core.serialization.object({
    status: core.serialization.lazy(async () => (await import("../../../../..")).common.ResponseStatus),
    message: core.serialization.string(),
});

export declare namespace DeleteJobResponse {
    interface Raw {
        status: serializers.common.ResponseStatus.Raw;
        message: string;
    }
}
