/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as RevertRevertApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const FieldDetailsTypeRequest: core.serialization.ObjectSchema<
    serializers.crm.FieldDetailsTypeRequest.Raw,
    RevertRevertApi.crm.FieldDetailsTypeRequest
> = core.serialization
    .object({
        additional: core.serialization.unknown(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).crm.FieldDetailsType));

export declare namespace FieldDetailsTypeRequest {
    interface Raw extends serializers.crm.FieldDetailsType.Raw {
        additional?: unknown;
    }
}
