/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const FieldDetailsTypeRead: core.serialization.ObjectSchema<
    serializers.crm.FieldDetailsTypeRead.Raw,
    Revert.crm.FieldDetailsTypeRead
> = core.serialization
    .object({
        isCustomField: core.serialization.boolean(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).crm.FieldDetailsType));

export declare namespace FieldDetailsTypeRead {
    interface Raw extends serializers.crm.FieldDetailsType.Raw {
        isCustomField: boolean;
    }
}
