/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const GetObjectPropertiesResponse: core.serialization.Schema<
    serializers.crm.GetObjectPropertiesResponse.Raw,
    Revert.crm.GetObjectPropertiesResponse
> = core.serialization.list(
    core.serialization.lazyObject(async () => (await import("../../../../..")).crm.FieldDetailsTypeRead)
);

export declare namespace GetObjectPropertiesResponse {
    type Raw = serializers.crm.FieldDetailsTypeRead.Raw[];
}
