/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const SetObjectPropertiesResponse: core.serialization.Schema<
    serializers.crm.SetObjectPropertiesResponse.Raw,
    Revert.crm.SetObjectPropertiesResponse
> = core.serialization.unknown();

export declare namespace SetObjectPropertiesResponse {
    type Raw = unknown;
}
