/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as RevertRevertApi from "../../../../../../api";
import * as core from "../../../../../../core";

export const SetObjectPropertiesRequest: core.serialization.ObjectSchema<
    serializers.crm.SetObjectPropertiesRequest.Raw,
    RevertRevertApi.crm.SetObjectPropertiesRequest
> = core.serialization.lazyObject(async () => (await import("../../../../..")).crm.FieldDetailsTypeRequest);

export declare namespace SetObjectPropertiesRequest {
    type Raw = serializers.crm.FieldDetailsTypeRequest.Raw;
}
