/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../../../..";

export interface DeleteDepartmentResponse {
    status: Revert.common.ResponseStatus;
    message: string;
}
