/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../../../..";

export interface GetDepartmentResponse {
    status: Revert.common.ResponseStatus;
    result?: unknown;
}
