/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateTelemetryEntryRequest {
    xRevertApiToken: string;
    numberOfUsers: number;
    numberOfAccounts: number;
    numberOfConnections: number;
    numberOfApiCalls: number;
}
