/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RevertRevertApi from "../../../../..";

export interface GetUserResponse {
    status: RevertRevertApi.common.ResponseStatus;
    result?: unknown;
}
