/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RevertRevertApi from "../../../../..";

export interface CommentTicket
    extends RevertRevertApi.common.CommonUnifiedFields,
        RevertRevertApi.common.CommentTicketWrite {}
