/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CompanyAddress {
    street?: string;
    city: string;
    state: string;
    country: string;
    zip: string;
    postalCode: string;
}
