/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../../../..";

export interface ContactWrite extends Revert.common.ContactRead {
    associations?: Revert.common.ContactAssociation;
}
