/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../../../..";

export interface Deal extends Vellum.common.CommonUnifiedFields, Vellum.common.DealWrite {}
