/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../../../..";

export interface Deal extends Revert.common.CommonUnifiedFields, Revert.common.DealRead {}
