/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EventRead {
    /** The type of the event in the CRM. */
    type: string;
    /** The Subject of the event/meeting in the CRM. */
    subject: string;
    /** Event start date time. */
    startDateTime: string;
    /** Event end date time. */
    endDateTime: string;
    /** Is `true` if the event is an all day event. */
    isAllDayEvent: boolean;
    /** Description of the event/meeting. */
    description: string;
    /** The location of the event/meeting. */
    location: string;
}
