/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../../../..";

export interface EventWrite extends Revert.common.EventRead {
    associations?: Revert.common.EventAssociation;
}
