/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../../../..";

export interface Lead extends Vellum.common.CommonUnifiedFields, Vellum.common.LeadWrite {}
