/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../../../..";

export interface Lead extends Revert.common.CommonUnifiedFields, Revert.common.LeadWrite {}
