/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Message {
    /** Message sent by user */
    text: string;
    /** Id of channel to which message was sent */
    channelId: string;
}
