/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../../../..";

export interface NoteWrite {
    /** The contents of the note in plain text or HTML. */
    content: string;
    associations?: Revert.common.DealAssociation;
}
