/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RevertRevertApi from "../../../../..";

export interface NoteWrite {
    /** The contents of the note in plain text or HTML. */
    content: string;
    associations?: RevertRevertApi.common.DealAssociation;
}
