/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RevertRevertApi from "../../../../..";

export interface Note extends RevertRevertApi.common.CommonUnifiedFields, RevertRevertApi.common.NoteWrite {}
