/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../../../..";

export interface NoteWrite extends Revert.common.NoteRead {
    associations?: Revert.common.DealAssociation;
}
