/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../../../..";

export interface TaskTicketWrite {
    /** Name of the task. */
    name: string;
    /** collection of IDs belonging to assignees. */
    assignees: string[];
    /** Description of the task. */
    description: string;
    /** Current status of the task. */
    status: Revert.common.TicketStatus;
    /** Priority of the task. */
    priority: Revert.common.TicketPriority;
    /** ID of the task creator. */
    creatorId: string;
    /** Due date for the given task. */
    dueDate: string;
    /** Date at which task was completed. */
    completedDate: string;
    /** Id of the parent task. */
    parentId: string;
    /** Id of the list */
    listId: string;
}
