/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UserWrite {
    /** The first name of a user in a CRM. */
    firstName: string;
    /** The last name of a user in a CRM. */
    lastName: string;
    /** The phone number of a user in a CRM. */
    phone: string;
    /** The email of a user in a CRM. */
    email: string;
}
