/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../../../../../..";

export interface GetFieldMappingResponse {
    canAddCustomMapping: boolean;
    mappableFields: Vellum.crm.fieldMapping.MappableFieldType[];
    fieldList?: unknown;
}
