/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Revert from "../../../../../../..";

export interface GetFieldMappingResponse {
    canAddCustomMapping: boolean;
    mappableFields: Revert.crm.fieldMapping.MappableFieldType[];
    fieldList?: unknown;
}
