/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RevertRevertApi from "../../../../../../..";

export interface MappableFieldType {
    fieldName: string;
    objectName: RevertRevertApi.common.StandardObject;
}
