/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Vellum from "../../../../../../api";
import * as core from "../../../../../../core";

export const CompanyAssociation: core.serialization.ObjectSchema<
    serializers.common.CompanyAssociation.Raw,
    Vellum.common.CompanyAssociation
> = core.serialization.object({
    dealId: core.serialization.string().optional(),
});

export declare namespace CompanyAssociation {
    interface Raw {
        dealId?: string | null;
    }
}
