/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const EventAssociation: core.serialization.ObjectSchema<
    serializers.common.EventAssociation.Raw,
    Revert.common.EventAssociation
> = core.serialization.object({
    dealId: core.serialization.string().optional(),
    contactId: core.serialization.string().optional(),
});

export declare namespace EventAssociation {
    interface Raw {
        dealId?: string | null;
        contactId?: string | null;
    }
}
