/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const CompanyAddress: core.serialization.ObjectSchema<
    serializers.common.CompanyAddress.Raw,
    Revert.common.CompanyAddress
> = core.serialization.object({
    street: core.serialization.string().optional(),
    city: core.serialization.string(),
    state: core.serialization.string(),
    country: core.serialization.string(),
    zip: core.serialization.string(),
    postalCode: core.serialization.string(),
});

export declare namespace CompanyAddress {
    interface Raw {
        street?: string | null;
        city: string;
        state: string;
        country: string;
        zip: string;
        postalCode: string;
    }
}
