/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const ContactWrite: core.serialization.ObjectSchema<
    serializers.common.ContactWrite.Raw,
    Revert.common.ContactWrite
> = core.serialization
    .object({
        associations: core.serialization
            .lazyObject(async () => (await import("../../../../..")).common.ContactAssociation)
            .optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).common.ContactRead));

export declare namespace ContactWrite {
    interface Raw extends serializers.common.ContactRead.Raw {
        associations?: serializers.common.ContactAssociation.Raw | null;
    }
}
