/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const LeadWrite: core.serialization.ObjectSchema<serializers.common.LeadWrite.Raw, Revert.common.LeadWrite> =
    core.serialization
        .object({
            associations: core.serialization
                .lazyObject(async () => (await import("../../../../..")).common.LeadAssociation)
                .optional(),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).common.LeadRead));

export declare namespace LeadWrite {
    interface Raw extends serializers.common.LeadRead.Raw {
        associations?: serializers.common.LeadAssociation.Raw | null;
    }
}
