/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const NoteRead: core.serialization.ObjectSchema<serializers.common.NoteRead.Raw, Revert.common.NoteRead> =
    core.serialization.object({
        content: core.serialization.string(),
    });

export declare namespace NoteRead {
    interface Raw {
        content: string;
    }
}
