/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const NoteWrite: core.serialization.ObjectSchema<serializers.common.NoteWrite.Raw, Revert.common.NoteWrite> =
    core.serialization
        .object({
            associations: core.serialization
                .lazyObject(async () => (await import("../../../../..")).common.DealAssociation)
                .optional(),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).common.NoteRead));

export declare namespace NoteWrite {
    interface Raw extends serializers.common.NoteRead.Raw {
        associations?: serializers.common.DealAssociation.Raw | null;
    }
}
