/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Chat } from "./api/resources/chat/client/Client";
import { Connection } from "./api/resources/connection/client/Client";
import { Crm } from "./api/resources/crm/client/Client";
import { Metadata } from "./api/resources/metadata/client/Client";
import { Ticket } from "./api/resources/ticket/client/Client";

export declare namespace RevertRevertApiClient {
    interface Options {
        environment?: core.Supplier<environments.RevertRevertApiEnvironment | string>;
    }

    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}

export class RevertRevertApiClient {
    constructor(protected readonly _options: RevertRevertApiClient.Options = {}) {}

    protected _chat: Chat | undefined;

    public get chat(): Chat {
        return (this._chat ??= new Chat(this._options));
    }

    protected _connection: Connection | undefined;

    public get connection(): Connection {
        return (this._connection ??= new Connection(this._options));
    }

    protected _crm: Crm | undefined;

    public get crm(): Crm {
        return (this._crm ??= new Crm(this._options));
    }

    protected _metadata: Metadata | undefined;

    public get metadata(): Metadata {
        return (this._metadata ??= new Metadata(this._options));
    }

    protected _ticket: Ticket | undefined;

    public get ticket(): Ticket {
        return (this._ticket ??= new Ticket(this._options));
    }
}
