/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const RevertRevertApiEnvironment = {
    Production: "https://api.revert.dev",
    /**
     * This staging environment is helpful for testing!
     */
    Staging: "https://api-staging.revert.dev",
    Local: "http://localhost:4001",
} as const;

export type RevertRevertApiEnvironment =
    | typeof RevertRevertApiEnvironment.Production
    | typeof RevertRevertApiEnvironment.Staging
    | typeof RevertRevertApiEnvironment.Local;
