/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const RevertEnvironment = {
    Production: "https://api.revert.dev",
    /**
     * This staging environment is helpful for testing!
     */
    Staging: "https://api-staging.revert.dev",
    Local: "http://localhost:4001",
} as const;

export type RevertEnvironment =
    | typeof RevertEnvironment.Production
    | typeof RevertEnvironment.Staging
    | typeof RevertEnvironment.Local;
