/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const CreateOrUpdateTaskRequest: core.serialization.ObjectSchema<
    serializers.ticket.CreateOrUpdateTaskRequest.Raw,
    Revert.ticket.CreateOrUpdateTaskRequest
> = core.serialization.lazyObject(async () => (await import("../../../../..")).common.TaskTicketWrite);

export declare namespace CreateOrUpdateTaskRequest {
    type Raw = serializers.common.TaskTicketWrite.Raw;
}
