/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as RevertRevertApi from "../../..";

export interface CrmMetadataResponse {
    status: string;
    data: RevertRevertApi.CrmMetadata[];
    error?: string;
}
