/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../..";

export interface CrmMetadataResponse {
    status: string;
    data: Vellum.CrmMetadata[];
    error?: string;
}
