/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vellum from "../../..";

export interface CrmMetadata {
    integrationId: string;
    name: string;
    imageSrc: string;
    status: Vellum.CrmStatus;
    clientId?: string;
    scopes: string[];
}
