/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Revert from "../../../../../../api";
import * as core from "../../../../../../core";

export const CreateorUpdateMessageRequest: core.serialization.ObjectSchema<
    serializers.chat.CreateorUpdateMessageRequest.Raw,
    Revert.chat.CreateorUpdateMessageRequest
> = core.serialization
    .object({})
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).common.Message));

export declare namespace CreateorUpdateMessageRequest {
    interface Raw extends serializers.common.Message.Raw {}
}
